import js from '@eslint/js';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';

// CONVENTION.md §11: @typescript-eslint strict, react-hooks, jsx-a11y strict.
export default tseslint.config(
    {
        ignores: [
            'vendor/**',
            'node_modules/**',
            'public/**',
            'bootstrap/ssr/**',
            'discovery/**',
            // Generated by `php artisan wayfinder:generate`.
            'resources/js/actions/**',
            'resources/js/routes/**',
            'resources/js/wayfinder/**',
        ],
    },
    js.configs.recommended,
    ...tseslint.configs.strict,
    {
        files: ['**/*.{ts,tsx}'],
        ...react.configs.flat.recommended,
        ...react.configs.flat['jsx-runtime'],
        ...jsxA11y.flatConfigs.strict,
        plugins: {
            react,
            'jsx-a11y': jsxA11y,
            'react-hooks': reactHooks,
        },
        languageOptions: {
            globals: { ...globals.browser },
        },
        settings: {
            react: { version: 'detect' },
        },
        rules: {
            ...react.configs.flat.recommended.rules,
            ...react.configs.flat['jsx-runtime'].rules,
            ...jsxA11y.flatConfigs.strict.rules,
            ...reactHooks.configs.recommended.rules,
            '@typescript-eslint/no-explicit-any': 'error',
            'react/no-danger': 'error',
            'react/prop-types': 'off',
            'no-console': 'warn',
        },
    },
    {
        files: ['*.config.{js,ts}'],
        languageOptions: {
            globals: { ...globals.node },
        },
    },
);
